name: Web
on:
  push:
    paths:
      - web/*
  pull_request:
    paths:
      - web/*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
      - uses: actions/checkout@master
      - run: yarn global add codacy-coverage
      - run: yarn --cwd web install
      - run: yarn --cwd web test
      - run: cat ./web/coverage/lcov.info | codacy-coverage
        env:
          CI: true
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
