name: Web
on:
  push:
    paths:
      - web/*
  pull_request:
    paths:
      - web/*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
      - uses: actions/checkout@master
      - run: yarn --cwd web install
      - run: yarn --cwd web test